#!/usr/bin/env bash
# A script that transfers a file from our client to a server
FILE_PATH=$1
IP=$2
USERNAME=$3
SSH_KEY_PATH=$4
DEST="$USERNAME@$IP:~/"

if [ $# -lt 4 ]; then
    echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY_PATH" "$FILE_PATH" "$DEST"
fi